### ISSUE TITLE
get_interfaces: AttributeError

### ISSUE THREAD

**Issue by SteanlyCZ** [d4vidcn/routeros_ssh_connector#23]
hi, i have a problem calling the function get_interfaces():

`Traceback (most recent call last):
  File "mk_02.py", line 5, in <module>
    interfaces = router.get_interfaces()
  File "/home/steanly/Venv/_pokusy/lib/python3.8/site-packages/routeros_ssh_connector/connector.py", line 70, in get_interfaces
    return self.parse_interfaces(self.net_connect.send_command("/interface print detail without-paging"))
  File "/home/steanly/Venv/_pokusy/lib/python3.8/site-packages/routeros_ssh_connector/connector.py", line 655, in parse_interfaces
    interface["name"] = re.search(r'name="(.*?)"', parsed).group(1)
AttributeError: 'NoneType' object has no attribute 'group'`

MK print:
```
[admin@MikroTik] > /interface print detail without-paging
Flags: D - dynamic, X - disabled, R - running, S - slave 
 0  R  name="ether1" default-name="ether1" type="ether" mtu=1500 actual-mtu=1500 l2mtu=1598 max-l2mtu=9214 mac-address=48:8F:5A:B8:49:B9 last-link-up-time=oct/22/2021 21:45:53 link-downs=0 

 1  RS name="ether2" default-name="ether2" type="ether" mtu=1500 actual-mtu=1500 l2mtu=1598 max-l2mtu=9214 mac-address=48:8F:5A:B8:49:BA last-link-up-time=oct/22/2021 21:45:54 link-downs=0 

 2   S name="ether3" default-name="ether3" type="ether" mtu=1500 actual-mtu=1500 l2mtu=1598 max-l2mtu=9214 mac-address=48:8F:5A:B8:49:BB link-downs=0 

 3   S name="ether4" default-name="ether4" type="ether" mtu=1500 actual-mtu=1500 l2mtu=1598 max-l2mtu=9214 mac-address=48:8F:5A:B8:49:BC link-downs=0 

 4  R  ;;; Description1
       name="ether5" default-name="ether5" type="ether" mtu=1500 actual-mtu=1500 l2mtu=1598 max-l2mtu=9214 mac-address=48:8F:5A:B8:49:BD last-link-up-time=oct/22/2021 21:45:53 link-downs=0 

 5  RS name="wlan1" default-name="wlan1" type="wlan" mtu=1500 actual-mtu=1500 l2mtu=1600 max-l2mtu=2290 mac-address=48:8F:5A:B8:49:BE last-link-up-time=oct/22/2021 21:46:02 link-downs=0 

 6  RS name="wlan2" default-name="wlan2" type="wlan" mtu=1500 actual-mtu=1500 l2mtu=1600 max-l2mtu=2290 mac-address=48:8F:5A:B8:49:BF last-link-up-time=oct/22/2021 21:48:37 link-downs=0 

 7   S name="wlan3" type="wlan" mtu=1500 actual-mtu=1500 l2mtu=1600 max-l2mtu=2290 mac-address=4A:8F:5A:B8:49:BE link-downs=0 

 8   S name="wlan4" type="wlan" mtu=1500 actual-mtu=1500 l2mtu=1600 max-l2mtu=2290 mac-address=4A:8F:5A:B8:49:BF link-downs=0 

 9   S name="wlan5" type="wlan" mtu=1500 actual-mtu=1500 l2mtu=1600 max-l2mtu=2290 mac-address=4A:8F:5A:B8:49:C0 link-downs=0 

10  R  name="MASTER" type="ovpn-out" mtu=1500 actual-mtu=1500 mac-address=02:99:E8:73:80:99 last-link-up-time=oct/22/2021 21:46:16 link-downs=0 

11  R  name="VDSL" type="pppoe-out" mtu=1480 actual-mtu=1480 last-link-up-time=oct/22/2021 21:46:11 link-downs=0 

12  R  ;;; Description2
       name="bridge1" type="bridge" mtu=auto actual-mtu=1500 l2mtu=1598 mac-address=4A:8F:5A:B8:49:C0 last-link-up-time=oct/22/2021 21:45:44 link-downs=0 

13  R  ;;; Description3
       name="bridge2" type="bridge" mtu=auto actual-mtu=1500 l2mtu=1600 mac-address=4A:8F:5A:B8:49:BE last-link-up-time=oct/22/2021 21:45:44 link-downs=0 

```

**Comment by VVRambo** [comment]
I've got the same problem, commenting here just to see if someone knows how to solve this.
